import {
  GoogleAdsAccount,
  Campaign,
  Keyword,
  SearchTerm,
  AdCreative,
  AnomalyAlert,
  AIInsight,
  BudgetRecommendation,
  AutomationRule,
  AuditLog,
  BreakdownItem,
  PerformanceMetric,
  SubscriptionPlan
} from '@/types/adoptimize';

export const INITIAL_ACCOUNT: GoogleAdsAccount = {
  id: 'acc-primary',
  clientCustomerId: 'Not Connected',
  accountName: 'Google Ads Account',
  currency: 'USD',
  timezone: 'America/New_York (UTC-5)',
  isConnected: false,
  lastSyncAt: new Date().toISOString(),
  syncStatus: 'IDLE',
  isDemo: false,
  totalCampaignsCount: 0,
  monthlySpendCap: 25000,
};

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-01',
    accountId: 'acc-google-8921-prod',
    name: 'Search - High Intent Core SaaS',
    type: 'SEARCH',
    status: 'ENABLED',
    budgetDaily: 160.00,
    spend: 4210.50,
    impressions: 48920,
    clicks: 2840,
    ctr: 5.80,
    cpc: 1.48,
    conversions: 148,
    cpa: 28.45,
    conversionValue: 19832.00,
    roas: 4.71,
    conversionRate: 5.21,
    healthStatus: 'HEALTHY',
    healthScore: 94,
    trendPoints: [38, 41, 45, 42, 50, 52, 58],
    historicalPoints: [
      { date: 'Sep 23', spend: 580, conversions: 21, cpa: 27.6, roas: 4.8 },
      { date: 'Sep 24', spend: 610, conversions: 22, cpa: 27.7, roas: 4.7 },
      { date: 'Sep 25', spend: 590, conversions: 20, cpa: 29.5, roas: 4.5 },
      { date: 'Sep 26', spend: 620, conversions: 23, cpa: 26.9, roas: 4.9 },
      { date: 'Sep 27', spend: 605, conversions: 21, cpa: 28.8, roas: 4.6 },
      { date: 'Sep 28', spend: 595, conversions: 20, cpa: 29.7, roas: 4.6 },
      { date: 'Sep 29', spend: 610, conversions: 21, cpa: 29.0, roas: 4.8 },
    ],
    previousPeriod: {
      spend: 3950.00,
      conversions: 132,
      cpa: 29.92,
      roas: 4.45,
    },
    keywordsCount: 24,
    activeAdsCount: 4,
    primaryGoal: 'TARGET_CPA',
  },
  {
    id: 'camp-02',
    accountId: 'acc-google-8921-prod',
    name: 'PMax - Enterprise Demo Inbound',
    type: 'PERFORMANCE_MAX',
    status: 'ENABLED',
    budgetDaily: 110.00,
    spend: 2940.00,
    impressions: 84310,
    clicks: 1920,
    ctr: 2.28,
    cpc: 1.53,
    conversions: 78,
    cpa: 37.69,
    conversionValue: 12480.00,
    roas: 4.24,
    conversionRate: 4.06,
    healthStatus: 'OPPORTUNITY',
    healthScore: 88,
    trendPoints: [28, 30, 31, 35, 34, 38, 42],
    historicalPoints: [
      { date: 'Sep 23', spend: 410, conversions: 11, cpa: 37.2, roas: 4.3 },
      { date: 'Sep 24', spend: 425, conversions: 12, cpa: 35.4, roas: 4.4 },
      { date: 'Sep 25', spend: 415, conversions: 11, cpa: 37.7, roas: 4.2 },
      { date: 'Sep 26', spend: 430, conversions: 12, cpa: 35.8, roas: 4.3 },
      { date: 'Sep 27', spend: 420, conversions: 11, cpa: 38.1, roas: 4.1 },
      { date: 'Sep 28', spend: 410, conversions: 10, cpa: 41.0, roas: 3.9 },
      { date: 'Sep 29', spend: 430, conversions: 11, cpa: 39.0, roas: 4.1 },
    ],
    previousPeriod: {
      spend: 2680.00,
      conversions: 68,
      cpa: 39.41,
      roas: 4.02,
    },
    keywordsCount: 16,
    activeAdsCount: 5,
    primaryGoal: 'TARGET_ROAS',
  },
  {
    id: 'camp-03',
    accountId: 'acc-google-8921-prod',
    name: 'Display - Retargeting & Brand Awareness',
    type: 'DISPLAY',
    status: 'ENABLED',
    budgetDaily: 75.00,
    spend: 1890.00,
    impressions: 215000,
    clicks: 1450,
    ctr: 0.67,
    cpc: 1.30,
    conversions: 9,
    cpa: 210.00,
    conversionValue: 1620.00,
    roas: 0.86,
    conversionRate: 0.62,
    healthStatus: 'CRITICAL',
    healthScore: 32,
    trendPoints: [60, 52, 44, 38, 30, 24, 18],
    historicalPoints: [
      { date: 'Sep 23', spend: 280, conversions: 2, cpa: 140.0, roas: 1.1 },
      { date: 'Sep 24', spend: 275, conversions: 2, cpa: 137.5, roas: 1.0 },
      { date: 'Sep 25', spend: 290, conversions: 1, cpa: 290.0, roas: 0.7 },
      { date: 'Sep 26', spend: 260, conversions: 2, cpa: 130.0, roas: 0.9 },
      { date: 'Sep 27', spend: 270, conversions: 1, cpa: 270.0, roas: 0.8 },
      { date: 'Sep 28', spend: 255, conversions: 1, cpa: 255.0, roas: 0.7 },
      { date: 'Sep 29', spend: 260, conversions: 0, cpa: 260.0, roas: 0.0 },
    ],
    previousPeriod: {
      spend: 1540.00,
      conversions: 18,
      cpa: 85.55,
      roas: 1.62,
    },
    keywordsCount: 12,
    activeAdsCount: 3,
    primaryGoal: 'MAXIMIZE_CONVERSIONS',
  },
  {
    id: 'camp-04',
    accountId: 'acc-google-8921-prod',
    name: 'Search - Competitor Conquesting',
    type: 'SEARCH',
    status: 'ENABLED',
    budgetDaily: 65.00,
    spend: 1720.00,
    impressions: 32100,
    clicks: 680,
    ctr: 2.12,
    cpc: 2.53,
    conversions: 19,
    cpa: 90.52,
    conversionValue: 3420.00,
    roas: 1.99,
    conversionRate: 2.79,
    healthStatus: 'WARNING',
    healthScore: 61,
    trendPoints: [42, 45, 39, 41, 35, 33, 30],
    historicalPoints: [
      { date: 'Sep 23', spend: 240, conversions: 3, cpa: 80.0, roas: 2.2 },
      { date: 'Sep 24', spend: 250, conversions: 3, cpa: 83.3, roas: 2.1 },
      { date: 'Sep 25', spend: 245, conversions: 3, cpa: 81.6, roas: 2.1 },
      { date: 'Sep 26', spend: 260, conversions: 3, cpa: 86.6, roas: 2.0 },
      { date: 'Sep 27', spend: 235, conversions: 2, cpa: 117.5, roas: 1.7 },
      { date: 'Sep 28', spend: 240, conversions: 3, cpa: 80.0, roas: 2.1 },
      { date: 'Sep 29', spend: 250, conversions: 2, cpa: 125.0, roas: 1.6 },
    ],
    previousPeriod: {
      spend: 1480.00,
      conversions: 22,
      cpa: 67.27,
      roas: 2.45,
    },
    keywordsCount: 18,
    activeAdsCount: 3,
    primaryGoal: 'TARGET_CPA',
  },
  {
    id: 'camp-05',
    accountId: 'acc-google-8921-prod',
    name: 'Search - Brand Exact Match',
    type: 'SEARCH',
    status: 'ENABLED',
    budgetDaily: 40.00,
    spend: 980.00,
    impressions: 18400,
    clicks: 2950,
    ctr: 16.03,
    cpc: 0.33,
    conversions: 162,
    cpa: 6.05,
    conversionValue: 14580.00,
    roas: 14.88,
    conversionRate: 5.49,
    healthStatus: 'HEALTHY',
    healthScore: 98,
    trendPoints: [70, 72, 75, 74, 78, 82, 85],
    historicalPoints: [
      { date: 'Sep 23', spend: 140, conversions: 24, cpa: 5.8, roas: 15.2 },
      { date: 'Sep 24', spend: 142, conversions: 23, cpa: 6.1, roas: 14.8 },
      { date: 'Sep 25', spend: 138, conversions: 22, cpa: 6.2, roas: 14.4 },
      { date: 'Sep 26', spend: 144, conversions: 25, cpa: 5.7, roas: 15.6 },
      { date: 'Sep 27', spend: 139, conversions: 23, cpa: 6.0, roas: 14.9 },
      { date: 'Sep 28', spend: 137, conversions: 22, cpa: 6.2, roas: 14.5 },
      { date: 'Sep 29', spend: 140, conversions: 23, cpa: 6.0, roas: 14.8 },
    ],
    previousPeriod: {
      spend: 920.00,
      conversions: 154,
      cpa: 5.97,
      roas: 15.10,
    },
    keywordsCount: 6,
    activeAdsCount: 2,
    primaryGoal: 'MAXIMIZE_CONVERSIONS',
  },
  {
    id: 'camp-06',
    accountId: 'acc-google-8921-prod',
    name: 'Shopping - Tier 1 Add-on Modules',
    type: 'SHOPPING',
    status: 'PAUSED',
    budgetDaily: 30.00,
    spend: 410.00,
    impressions: 14200,
    clicks: 310,
    ctr: 2.18,
    cpc: 1.32,
    conversions: 5,
    cpa: 82.00,
    conversionValue: 590.00,
    roas: 1.44,
    conversionRate: 1.61,
    healthStatus: 'WARNING',
    healthScore: 54,
    trendPoints: [30, 28, 25, 20, 18, 15, 12],
    historicalPoints: [
      { date: 'Sep 23', spend: 60, conversions: 1, cpa: 60.0, roas: 1.6 },
      { date: 'Sep 24', spend: 65, conversions: 1, cpa: 65.0, roas: 1.5 },
      { date: 'Sep 25', spend: 55, conversions: 1, cpa: 55.0, roas: 1.8 },
      { date: 'Sep 26', spend: 60, conversions: 1, cpa: 60.0, roas: 1.5 },
      { date: 'Sep 27', spend: 70, conversions: 1, cpa: 70.0, roas: 1.3 },
      { date: 'Sep 28', spend: 50, conversions: 0, cpa: 50.0, roas: 0.0 },
      { date: 'Sep 29', spend: 50, conversions: 0, cpa: 50.0, roas: 0.0 },
    ],
    previousPeriod: {
      spend: 780.00,
      conversions: 14,
      cpa: 55.71,
      roas: 2.12,
    },
    keywordsCount: 8,
    activeAdsCount: 2,
    primaryGoal: 'TARGET_ROAS',
  }
];

export const MOCK_KEYWORDS: Keyword[] = [
  {
    id: 'kw-01',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    keyword: 'cloud database monitoring software',
    matchType: 'EXACT',
    spend: 1140.00,
    clicks: 720,
    impressions: 9800,
    ctr: 7.35,
    cpc: 1.58,
    conversions: 54,
    cpa: 21.11,
    qualityScore: 9,
    status: 'ENABLED',
    flag: 'TOP_PERFORMER',
  },
  {
    id: 'kw-02',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    keyword: 'enterprise postgresql performance tool',
    matchType: 'PHRASE',
    spend: 890.00,
    clicks: 480,
    impressions: 7400,
    ctr: 6.49,
    cpc: 1.85,
    conversions: 36,
    cpa: 24.72,
    qualityScore: 8,
    status: 'ENABLED',
    flag: 'TOP_PERFORMER',
  },
  {
    id: 'kw-03',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    keyword: 'sql query optimization platform',
    matchType: 'BROAD',
    spend: 920.00,
    clicks: 610,
    impressions: 14200,
    ctr: 4.30,
    cpc: 1.51,
    conversions: 14,
    cpa: 65.71,
    qualityScore: 6,
    status: 'ENABLED',
    flag: 'RISING_CPA',
  },
  {
    id: 'kw-04',
    campaignId: 'camp-03',
    campaignName: 'Display - Retargeting & Brand Awareness',
    keyword: 'database administration training course',
    matchType: 'BROAD',
    spend: 540.00,
    clicks: 390,
    impressions: 48000,
    ctr: 0.81,
    cpc: 1.38,
    conversions: 0,
    cpa: 540.00,
    qualityScore: 4,
    status: 'ENABLED',
    flag: 'HIGH_SPEND_ZERO_CONV',
  },
  {
    id: 'kw-05',
    campaignId: 'camp-04',
    campaignName: 'Search - Competitor Conquesting',
    keyword: 'datadog database monitoring pricing',
    matchType: 'EXACT',
    spend: 680.00,
    clicks: 220,
    impressions: 9100,
    ctr: 2.42,
    cpc: 3.09,
    conversions: 10,
    cpa: 68.00,
    qualityScore: 7,
    status: 'ENABLED',
    flag: 'NORMAL',
  },
  {
    id: 'kw-06',
    campaignId: 'camp-04',
    campaignName: 'Search - Competitor Conquesting',
    keyword: 'new relic alternatives for postgres',
    matchType: 'PHRASE',
    spend: 490.00,
    clicks: 160,
    impressions: 8300,
    ctr: 1.93,
    cpc: 3.06,
    conversions: 3,
    cpa: 163.33,
    qualityScore: 5,
    status: 'ENABLED',
    flag: 'RISING_CPA',
  },
  {
    id: 'kw-07',
    campaignId: 'camp-05',
    campaignName: 'Search - Brand Exact Match',
    keyword: 'cloudscale',
    matchType: 'EXACT',
    spend: 580.00,
    clicks: 1780,
    impressions: 11200,
    ctr: 15.89,
    cpc: 0.33,
    conversions: 104,
    cpa: 5.58,
    qualityScore: 10,
    status: 'ENABLED',
    flag: 'TOP_PERFORMER',
  },
  {
    id: 'kw-08',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    keyword: 'free database performance checker',
    matchType: 'BROAD',
    spend: 420.00,
    clicks: 340,
    impressions: 8900,
    ctr: 3.82,
    cpc: 1.24,
    conversions: 1,
    cpa: 420.00,
    qualityScore: 4,
    status: 'ENABLED',
    flag: 'HIGH_SPEND_ZERO_CONV',
  }
];

export const MOCK_SEARCH_TERMS: SearchTerm[] = [
  {
    id: 'st-01',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    searchTerm: 'database administrator salary in new york',
    impressions: 3400,
    clicks: 142,
    spend: 218.40,
    conversions: 0,
    cpa: 0,
    recommendedAction: 'ADD_NEGATIVE',
    wastedSpendEstimate: 218.40,
    intentRelevance: 'LOW',
    status: 'ACTIVE',
  },
  {
    id: 'st-02',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    searchTerm: 'free sql optimizer online crack download',
    impressions: 2100,
    clicks: 98,
    spend: 142.10,
    conversions: 0,
    cpa: 0,
    recommendedAction: 'ADD_NEGATIVE',
    wastedSpendEstimate: 142.10,
    intentRelevance: 'LOW',
    status: 'ACTIVE',
  },
  {
    id: 'st-03',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    searchTerm: 'best postgres latency monitor for kubernetes',
    impressions: 1950,
    clicks: 164,
    spend: 246.00,
    conversions: 16,
    cpa: 15.38,
    recommendedAction: 'ADD_KEYWORD',
    wastedSpendEstimate: 0,
    intentRelevance: 'HIGH',
    status: 'ACTIVE',
  },
  {
    id: 'st-04',
    campaignId: 'camp-04',
    campaignName: 'Search - Competitor Conquesting',
    searchTerm: 'datadog login portal support phone number',
    impressions: 1800,
    clicks: 74,
    spend: 228.60,
    conversions: 0,
    cpa: 0,
    recommendedAction: 'ADD_NEGATIVE',
    wastedSpendEstimate: 228.60,
    intentRelevance: 'LOW',
    status: 'ACTIVE',
  },
  {
    id: 'st-05',
    campaignId: 'camp-02',
    campaignName: 'PMax - Enterprise Demo Inbound',
    searchTerm: 'enterprise database monitoring software demo',
    impressions: 4200,
    clicks: 280,
    spend: 428.40,
    conversions: 24,
    cpa: 17.85,
    recommendedAction: 'ADD_KEYWORD',
    wastedSpendEstimate: 0,
    intentRelevance: 'HIGH',
    status: 'ACTIVE',
  }
];

export const MOCK_ADS: AdCreative[] = [
  {
    id: 'ad-01',
    campaignId: 'camp-01',
    headline1: 'Fast PostgreSQL Performance',
    headline2: 'Detect Slow Queries in Seconds',
    headline3: 'Start Free 14-Day Trial',
    description1: 'Continuously track database health, query latency, and resource bottlenecks.',
    description2: 'Over 1,200 DevOps teams trust CloudScale. Setup in under 5 minutes.',
    finalUrl: 'https://cloudscale.io/database-monitoring',
    adStrength: 'EXCELLENT',
    impressions: 28400,
    clicks: 1690,
    ctr: 5.95,
    conversions: 94,
    cpa: 26.80,
    status: 'ENABLED',
    aiCritique: 'Strong conversion rate with direct value proposition. High keyword intent alignment.',
  },
  {
    id: 'ad-02',
    campaignId: 'camp-01',
    headline1: 'Database Tool for Modern Teams',
    headline2: 'See System Metrics',
    headline3: 'Learn More Today',
    description1: 'Check out our comprehensive suite of developer and sysadmin infrastructure tools.',
    description2: 'Contact our sales engineering team for pricing and trial options.',
    finalUrl: 'https://cloudscale.io/product-overview',
    adStrength: 'POOR',
    impressions: 14200,
    clicks: 420,
    ctr: 2.95,
    conversions: 8,
    cpa: 78.40,
    status: 'ENABLED',
    aiCritique: 'Vague headlines lacking clear urgency or benefit. Weak CTA ("Learn More") hurts conversion rate by ~48%.',
  },
  {
    id: 'ad-03',
    campaignId: 'camp-03',
    headline1: 'CloudScale Infrastructure',
    headline2: 'Powering Global Databases',
    headline3: 'Explore CloudScale',
    description1: 'Transform how your engineering department provisions and monitors cloud workloads.',
    description2: 'Enterprise-grade security and SOC2 compliance built-in.',
    finalUrl: 'https://cloudscale.io/enterprise',
    adStrength: 'AVERAGE',
    impressions: 110000,
    clicks: 680,
    ctr: 0.61,
    conversions: 3,
    cpa: 294.00,
    status: 'ENABLED',
    aiCritique: 'Broad display creative yielding low engagement. Needs specific problem-focused messaging to filter unqualified clicks.',
  }
];

export const MOCK_DEVICE_BREAKDOWN: BreakdownItem[] = [
  { name: 'Desktop', spend: 7120.00, conversions: 298, cpa: 23.89, roas: 5.42, sharePercent: 63.8 },
  { name: 'Mobile', spend: 3640.50, conversions: 96, cpa: 37.92, roas: 3.12, sharePercent: 32.6 },
  { name: 'Tablet', spend: 390.00, conversions: 18, cpa: 21.66, roas: 4.88, sharePercent: 3.6 },
];

export const MOCK_LOCATION_BREAKDOWN: BreakdownItem[] = [
  { name: 'United States', spend: 6840.00, conversions: 274, cpa: 24.96, roas: 5.10, sharePercent: 61.3 },
  { name: 'United Kingdom', spend: 1840.00, conversions: 62, cpa: 29.67, roas: 4.22, sharePercent: 16.5 },
  { name: 'Germany', spend: 1220.00, conversions: 41, cpa: 29.75, roas: 4.30, sharePercent: 10.9 },
  { name: 'Canada', spend: 760.50, conversions: 24, cpa: 31.68, roas: 3.85, sharePercent: 6.8 },
  { name: 'Australia', spend: 490.00, conversions: 11, cpa: 44.54, roas: 2.80, sharePercent: 4.5 },
];

export const MOCK_ANOMALIES: AnomalyAlert[] = [
  {
    id: 'anom-01',
    campaignId: 'camp-03',
    campaignName: 'Display - Retargeting & Brand Awareness',
    metric: 'CPA',
    severity: 'CRITICAL',
    title: 'Severe CPA Spike (+145%) in Retargeting Campaign',
    whatChanged: 'CPA rose from $85.55 to $210.00 over the past 7 days while conversions dropped 50%.',
    whenChanged: 'Detected 18 hours ago',
    whyItMatters: 'Campaign consumed $1,890 of monthly advertising budget with only 9 conversions, causing ROAS to drop to 0.86 (unprofitable).',
    recommendedAction: 'Reduce daily budget from $75/day to $25/day and pause broad non-converting placements.',
    detectedAt: '2026-09-29T06:14:00Z',
    resolved: false,
    autoExecutable: true,
  },
  {
    id: 'anom-02',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    metric: 'SPEND',
    severity: 'OPPORTUNITY',
    title: 'Budget Exhaustion on Top Converting Campaign',
    whatChanged: 'Campaign is hitting 100% of its $160/day daily budget cap by 3:30 PM EST every day.',
    whenChanged: 'Detected 1 day ago',
    whyItMatters: 'High-performing traffic (ROAS 4.71, CPA $28.45) is losing ~28% search impression share due to budget constraints.',
    recommendedAction: 'Increase daily budget from $160/day to $210/day by reallocating underperforming display spend.',
    detectedAt: '2026-09-28T15:30:00Z',
    resolved: false,
    autoExecutable: true,
  },
  {
    id: 'anom-03',
    campaignId: 'camp-04',
    campaignName: 'Search - Competitor Conquesting',
    metric: 'CPC',
    severity: 'WARNING',
    title: 'CPC Surge (+34%) in Competitor Bidding',
    whatChanged: 'Average CPC rose from $1.88 to $2.53 due to aggressive competitor bidding auction activity.',
    whenChanged: 'Detected 2 days ago',
    whyItMatters: 'Conquesting CPA climbed from $67.27 to $90.52, threatening positive campaign margin.',
    recommendedAction: 'Switch bidding strategy to Target CPA with a $70 hard cap or focus only on exact match keywords.',
    detectedAt: '2026-09-27T11:20:00Z',
    resolved: false,
    autoExecutable: false,
  },
  {
    id: 'anom-04',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    metric: 'CTR',
    severity: 'WARNING',
    title: 'Irrelevant Search Term Spend Leak Detected',
    whatChanged: '2 broad search queries ("administrator salary", "free crack download") spent $360.50 with 0 conversions.',
    whenChanged: 'Detected 3 days ago',
    whyItMatters: 'Budget is leaking on job seekers and free tool seekers rather than enterprise buyers.',
    recommendedAction: 'Add [salary], [jobs], and [crack download] as negative exact phrase keywords.',
    detectedAt: '2026-09-26T14:45:00Z',
    resolved: false,
    autoExecutable: true,
  }
];

export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ins-01',
    campaignId: 'camp-03',
    campaignName: 'Display - Retargeting & Brand Awareness',
    category: 'CRITICAL_ISSUE',
    problem: 'Campaign CPA increased 145% while ROAS fell below 1.0 (currently 0.86), resulting in negative operating return.',
    whyItMatters: 'Campaign has consumed $1,890 in the last 7 days but produced only 9 conversions. You are losing approximately $270 per day in unrecoverable ad spend compared to benchmark efficiency.',
    evidence: {
      metric: 'CPA & ROAS',
      before: '$85.55 CPA / 1.62 ROAS',
      current: '$210.00 CPA / 0.86 ROAS',
      changePercent: '+145.5% CPA, -46.9% ROAS',
      context: 'Based on 215,000 display impressions and 9 conversions recorded over the last 7 days.',
    },
    recommendedAction: 'Reduce daily budget from $75/day to $25/day immediately. Exclude mobile app placements and non-converting audience segments.',
    expectedImpact: 'Saves ~$1,500/month in wasted spend while preserving core high-intent site visitor retargeting.',
    confidence: 96,
    status: 'NEW',
    createdAt: '2026-09-29T10:00:00Z',
    actionPayload: {
      type: 'BUDGET_CHANGE',
      targetId: 'camp-03',
      targetName: 'Display - Retargeting & Brand Awareness',
      oldValue: 75,
      newValue: 25,
    }
  },
  {
    id: 'ins-02',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    category: 'BUDGET_OPPORTUNITY',
    problem: 'High-performing campaign is severely budget-constrained and losing 28.4% of eligible high-intent search impression share.',
    whyItMatters: 'With a CPA of $28.45 and ROAS of 4.71, this campaign is your most profitable customer acquisition channel. Capping it at $160/day leaves an estimated 18-24 qualified signups on the table each month.',
    evidence: {
      metric: 'Impression Share Lost to Budget',
      before: '14.2%',
      current: '28.4%',
      changePercent: '+100.0% lost share',
      context: 'Campaign hits daily spend ceiling before 4 PM in 6 out of the past 7 days.',
    },
    recommendedAction: 'Increase daily budget from $160/day to $210/day (+31.2%). Funds can be reallocated directly from the underperforming Display campaign.',
    expectedImpact: 'Projected +22 conversions/month (+$2,940 gross monthly margin at 4.7 ROAS).',
    confidence: 93,
    status: 'NEW',
    createdAt: '2026-09-29T09:30:00Z',
    actionPayload: {
      type: 'BUDGET_CHANGE',
      targetId: 'camp-01',
      targetName: 'Search - High Intent Core SaaS',
      oldValue: 160,
      newValue: 210,
    }
  },
  {
    id: 'ins-03',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    category: 'WASTED_SPEND',
    problem: 'Broad match query leakage is draining budget on job-search and non-commercial queries.',
    whyItMatters: 'Search terms such as "database administrator salary" and "free online crack" spent $360.50 without yielding a single signup or demo request.',
    evidence: {
      metric: 'Zero-Conversion Search Term Spend',
      before: '$48.00',
      current: '$360.50',
      changePercent: '+651%',
      context: '4 search terms generated 240 clicks and 0 conversions over the last 14 days.',
    },
    recommendedAction: 'Add negative keyword list: ["salary", "resume", "crack", "download free", "jobs"].',
    expectedImpact: 'Immediately recovers ~$720/month in wasted clicks and redirects spend to buying-intent searches.',
    confidence: 99,
    status: 'NEW',
    createdAt: '2026-09-28T18:00:00Z',
    actionPayload: {
      type: 'ADD_NEGATIVE_KEYWORD',
      targetId: 'camp-01',
      targetName: 'Search - High Intent Core SaaS',
      oldValue: '0 negative keywords',
      newValue: '5 negative keywords',
    }
  },
  {
    id: 'ins-04',
    campaignId: 'camp-02',
    campaignName: 'PMax - Enterprise Demo Inbound',
    category: 'GROWTH_OPPORTUNITY',
    problem: 'Target ROAS bidding is over-restricting bid aggressiveness during peak B2B weekday conversion hours.',
    whyItMatters: 'Between 9:00 AM and 3:00 PM EST (Tuesday through Thursday), conversion rate reaches 6.8%, but Google Ads smart bidding bids uniformly across all hours.',
    evidence: {
      metric: 'B2B Peak Hour Conversion Rate',
      before: '4.06% avg',
      current: '6.82% peak',
      changePercent: '+67.9% higher CR',
      context: 'Calculated from 1,920 clicks over the last 30 days.',
    },
    recommendedAction: 'Implement an ad schedule bid adjustment of +15% during Tuesday-Thursday 9 AM - 4 PM EST.',
    expectedImpact: 'Estimated +12% increase in demo bookings at steady CPA.',
    confidence: 89,
    status: 'REVIEWED',
    createdAt: '2026-09-27T12:00:00Z',
  },
  {
    id: 'ins-05',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    category: 'PERFORMANCE_IMPROVEMENT',
    problem: 'Ad creative "Database Tool for Modern Teams" has a low CTR (2.95%) and a poor CPA ($78.40) dragging down group ad score.',
    whyItMatters: 'Google is serving this variant on 33% of impressions, suppressing overall Quality Score and inflating average CPC by an estimated $0.24.',
    evidence: {
      metric: 'Ad CTR & CPA vs Group Benchmark',
      before: '5.80% CTR / $28.45 CPA',
      current: '2.95% CTR / $78.40 CPA',
      changePercent: '-49.1% CTR, +175% CPA',
      context: 'Based on 14,200 impressions for Ad ID ad-02.',
    },
    recommendedAction: 'Pause Ad ID ad-02 and replace with a high-intent headline emphasizing query latency benchmark speed.',
    expectedImpact: 'Improves ad group Quality Score from 7/10 to 8/10 and lowers blended CPC.',
    confidence: 94,
    status: 'NEW',
    createdAt: '2026-09-28T08:15:00Z',
    actionPayload: {
      type: 'PAUSE_KEYWORD',
      targetId: 'ad-02',
      targetName: 'Ad #2 (Database Tool)',
      oldValue: 'ENABLED',
      newValue: 'PAUSED',
    }
  }
];

export const MOCK_BUDGET_RECOMMENDATIONS: BudgetRecommendation[] = [
  {
    id: 'bud-rec-01',
    campaignFromId: 'camp-03',
    campaignFromName: 'Display - Retargeting & Brand Awareness',
    campaignToId: 'camp-01',
    campaignToName: 'Search - High Intent Core SaaS',
    currentBudgetFrom: 75.00,
    proposedBudgetFrom: 25.00,
    currentBudgetTo: 160.00,
    proposedBudgetTo: 210.00,
    reallocatedAmount: 50.00,
    reason: 'Display retargeting CPA ($210.00) is 7.4x higher than Search High Intent ($28.45). Moving $50/day into Search captures high-converting search volume that is currently capped by budget.',
    supportingMetrics: {
      fromRoas: 0.86,
      toRoas: 4.71,
      fromCpa: 210.00,
      toCpa: 28.45,
      fromSpend: 1890.00,
      toSpend: 4210.50,
    },
    estimatedMonthlyImpact: '+$4,230/mo net profit (+36 additional conversions, -$1,500 wasted spend)',
    status: 'PENDING',
  },
  {
    id: 'bud-rec-02',
    campaignFromId: 'camp-04',
    campaignFromName: 'Search - Competitor Conquesting',
    campaignToId: 'camp-02',
    campaignToName: 'PMax - Enterprise Demo Inbound',
    currentBudgetFrom: 65.00,
    proposedBudgetFrom: 45.00,
    currentBudgetTo: 110.00,
    proposedBudgetTo: 130.00,
    reallocatedAmount: 20.00,
    reason: 'Competitor CPC spiked 34% leading to elevated $90.52 CPA. Performance Max is yielding steady $37.69 CPA and 4.24 ROAS with room for scaling.',
    supportingMetrics: {
      fromRoas: 1.99,
      toRoas: 4.24,
      fromCpa: 90.52,
      toCpa: 37.69,
      fromSpend: 1720.00,
      toSpend: 2940.00,
    },
    estimatedMonthlyImpact: '+$1,120/mo revenue (+14 high-value enterprise demo leads)',
    status: 'PENDING',
  }
];

export const MOCK_AUTOMATION_RULES: AutomationRule[] = [
  {
    id: 'rule-01',
    name: 'Emergency CPA Bleed Safeguard',
    category: 'AUTO_OPTIMIZE',
    conditionDescription: 'If campaign 7-day CPA exceeds $150 and spend exceeds $500',
    conditionMetric: 'CPA',
    conditionOperator: '>',
    conditionValue: 150,
    durationDays: 7,
    actionType: 'RECOMMEND_BUDGET_CUT',
    actionDescription: 'Reduce daily budget by 30% and notify account lead',
    enabled: true,
    requiresApproval: true,
    maxBudgetShiftLimitPercent: 15,
    lastTriggeredAt: '2026-09-29T06:14:00Z',
    executionCount: 2,
  },
  {
    id: 'rule-02',
    name: 'Zero-Conversion Keyword Flag & Pause',
    category: 'RECOMMEND',
    conditionDescription: 'If keyword spend exceeds $200 with 0 conversions',
    conditionMetric: 'SPEND_NO_CONV',
    conditionOperator: '>',
    conditionValue: 200,
    durationDays: 14,
    actionType: 'FLAG_KEYWORD',
    actionDescription: 'Flag keyword for negative match review and notify',
    enabled: true,
    requiresApproval: false,
    maxBudgetShiftLimitPercent: 0,
    lastTriggeredAt: '2026-09-28T14:45:00Z',
    executionCount: 4,
  },
  {
    id: 'rule-03',
    name: 'ROAS Plummet Monitor',
    category: 'MONITOR',
    conditionDescription: 'If campaign ROAS falls below 1.2 for 3 consecutive days',
    conditionMetric: 'ROAS',
    conditionOperator: '<',
    conditionValue: 1.2,
    durationDays: 3,
    actionType: 'NOTIFY',
    actionDescription: 'Send high-priority slack and email alert',
    enabled: true,
    requiresApproval: false,
    maxBudgetShiftLimitPercent: 0,
    lastTriggeredAt: '2026-09-27T08:00:00Z',
    executionCount: 5,
  },
  {
    id: 'rule-04',
    name: 'High Performance Budget Expansion',
    category: 'AUTO_OPTIMIZE',
    conditionDescription: 'If ROAS > 4.0 and impression share lost to budget > 20%',
    conditionMetric: 'ROAS',
    conditionOperator: '>',
    conditionValue: 4.0,
    durationDays: 5,
    actionType: 'RECOMMEND_BUDGET_CUT',
    actionDescription: 'Draft a +15% budget scaling proposal for approval',
    enabled: false,
    requiresApproval: true,
    maxBudgetShiftLimitPercent: 15,
    executionCount: 0,
  }
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-01',
    timestamp: '2026-09-29T14:10:00Z',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    actionType: 'NEGATIVE_KEYWORD_ADDED',
    previousValue: 'None',
    newValue: '["administrator salary", "crack download"]',
    reason: 'Zero-conversion query leakage consuming $360.50 ad spend.',
    source: 'AI_RECOMMENDATION',
    userOrSystem: 'Jay Rathod (via AI One-Click Apply)',
    status: 'EXECUTED',
    canRevert: true,
  },
  {
    id: 'audit-02',
    timestamp: '2026-09-28T19:30:00Z',
    campaignId: 'camp-06',
    campaignName: 'Shopping - Tier 1 Add-on Modules',
    actionType: 'CAMPAIGN_STATUS_CHANGE',
    previousValue: 'ENABLED',
    newValue: 'PAUSED',
    reason: 'Low conversion volume and rising CPA ($82.00 vs $50.00 target).',
    source: 'USER',
    userOrSystem: 'Jay Rathod',
    status: 'EXECUTED',
    canRevert: true,
  },
  {
    id: 'audit-03',
    timestamp: '2026-09-27T11:45:00Z',
    campaignId: 'camp-01',
    campaignName: 'Search - High Intent Core SaaS',
    actionType: 'BUDGET_CHANGE',
    previousValue: '$140.00/day',
    newValue: '$160.00/day',
    reason: 'Scaled budget to capture high ROAS (4.71) demand.',
    source: 'AUTOMATION_RULE',
    userOrSystem: 'Rule #4: High Performance Budget Expansion',
    status: 'EXECUTED',
    canRevert: true,
  }
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'FREE',
    name: 'Starter Plan',
    description: 'Essential monitoring for businesses starting with Google Ads.',
    monthlyPrice: 0,
    annualPriceMonthly: 0,
    accountLimit: '1 Google Ads Account',
    spendLimit: 'Up to $2,500/mo spend',
    features: [
      'Daily campaign health scan',
      'Basic anomaly alerts (CPA spikes)',
      'Last 14 days historical analysis',
      'Manual budget change recommendations',
      'Standard email notifications',
    ],
  },
  {
    id: 'PRO',
    name: 'Performance Pro',
    description: 'Designed for scaling SaaS, ecommerce, and performance marketers.',
    monthlyPrice: 79,
    annualPriceMonthly: 64,
    badge: 'MOST POPULAR',
    popular: true,
    accountLimit: 'Up to 5 Google Ads Accounts',
    spendLimit: 'Up to $35,000/mo spend',
    features: [
      'Continuous 15-minute sync & monitoring',
      'AI Marketing Analyst with grounded root-cause logic',
      'One-click Budget Optimizer simulator',
      'Search term waste & negative keyword extractor',
      'AI Marketing Copilot with account memory',
      'Automation rules with safeguard limits',
      'Comprehensive audit logs with 1-click revert',
      'Executive performance reports & PDF export',
    ],
  },
  {
    id: 'BUSINESS',
    name: 'Agency & Scale',
    description: 'For marketing agencies, multi-brand founders, and high spenders.',
    monthlyPrice: 199,
    annualPriceMonthly: 159,
    accountLimit: 'Unlimited Google Ads Accounts',
    spendLimit: 'Unlimited monthly ad spend',
    features: [
      'Everything in Pro plan',
      'Multi-client agency dashboard & roll-up reporting',
      'Custom webhook & Slack team alerts',
      'Dedicated Google Ads API quota management',
      'Custom automation rule builder with multi-step triggers',
      'White-label executive client reports',
      'Priority engineer & marketing analyst support',
    ],
  }
];

export function computeAccountMetrics(campaigns: Campaign[]): PerformanceMetric {
  const totals = campaigns.reduce(
    (acc, c) => {
      acc.spend += c.spend;
      acc.impressions += c.impressions;
      acc.clicks += c.clicks;
      acc.conversions += c.conversions;
      acc.conversionValue += c.conversionValue;
      return acc;
    },
    { spend: 0, impressions: 0, clicks: 0, conversions: 0, conversionValue: 0 }
  );

  const ctr = totals.impressions > 0 ? (totals.clicks / totals.impressions) * 100 : 0;
  const cpc = totals.clicks > 0 ? totals.spend / totals.clicks : 0;
  const cpa = totals.conversions > 0 ? totals.spend / totals.conversions : 0;
  const roas = totals.spend > 0 ? totals.conversionValue / totals.spend : 0;
  const conversionRate = totals.clicks > 0 ? (totals.conversions / totals.clicks) * 100 : 0;

  return {
    spend: totals.spend,
    impressions: totals.impressions,
    clicks: totals.clicks,
    conversions: totals.conversions,
    conversionValue: totals.conversionValue,
    ctr,
    cpc,
    cpa,
    roas,
    conversionRate,
  };
}
